name: Task Management CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  ci:
    name: Lint, Test & Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: true

      - name: Build UI Library (dependency)
        working-directory: ./fb-ui-library
        run: pnpm build

      - name: Lint
        working-directory: ./fb-task-management
        run: pnpm lint

      - name: Run unit tests
        working-directory: ./fb-task-management
        run: pnpm test

      - name: Build project
        working-directory: ./fb-task-management
        run: pnpm build

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: fb-task-management-coverage
          path: fb-task-management/coverage/
          retention-days: 30

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fb-task-management-build
          path: fb-task-management/.next/
          retention-days: 7