name: E2E Tests

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_run:
    workflows: ["Task Management CI"]
    types: [completed]
    branches: [main, master, develop]

jobs:
  e2e:
    name: Playwright E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    # Only run E2E if CI workflow succeeded (for workflow_run trigger)
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: true

      - name: Build project (needed for E2E)
        run: pnpm --filter task-management build

      - name: Install Playwright Browsers
        run: pnpm --filter task-management exec playwright install --with-deps

      - name: Start development server
        run: pnpm --filter task-management dev &
        
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run Playwright E2E tests
        run: pnpm --filter task-management exec playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: fb-task-management/playwright-report/
          retention-days: 30
